<?php

namespace Database\Seeders;

use App\Models\Position;
use Illuminate\Database\Seeder;

class PositionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $positions = [
            'Accountant I',
            'Accountant II',
            'Accountant III',
            'Administrative Aide I',
            'Administrative Aide II',
            'Administrative Aide III',
            'Administrative Aide IV',
            'Administrative Aide VI',
            'Administrative Assistant I',
            'Administrative Assistant II',
            'Administrative Assistant III',
            'Administrative Officer I',
            'Administrative Officer II',
            'Administrative Officer III',
            'Administrative Officer IV',
            'Administrative Officer V',
            'Attorney I',
            'Attorney II',
            'Attorney III',
            'Attorney IV',
            'Bookkeeper',
            'Budget Assistant',
            'Cash Clerk I',
            'Cash Clerk II',
            'Cash Clerk III',
            'Chief Administrative Officer',
            'Community Development Assistant I',
            'Community Development Assistant II',
            'Community Development Officer I',
            'Community Development Officer II',
            'Community Development Officer III',
            'Community Development Officer IV',
            'Community Development Officer V',
            'Community Empowerment Facilitator',
            'Community Facilitator',
            'Community Facilitator Aide',
            'Computer Maintenance Technologist I',
            'Computer Maintenance Technologist II',
            'Computer Maintenance Technologist III',
            'Cook I',
            'Cook II',
            'Deputy Regional Project Manager',
            'Director I',
            'Director II',
            'Director III',
            'Director IV',
            'Director V',
            'Director VI',
            'Engineer II',
            'Engineer III',
            'Executive Assistant',
            'Financial Analyst I',
            'Financial Analyst II',
            'Financial Analyst III',
            'Houseparent I',
            'Houseparent II',
            'Houseparent III',
            'Information Officer I',
            'Information Officer II',
            'Information Systems Analyst I',
            'Information Systems Analyst II',
            'Information Systems Analyst III',
            'Information Technology Officer I',
            'Information Technology Officer II',
            'Laundry Worker I',
            'Laundry Worker II',
            'Legal Assistant I',
            'Legal Assistant II',
            'Management and Audit Analyst I',
            'Management and Audit Analyst II',
            'Management and Audit Analyst III',
            'Manpower Development Officer I',
            'Manpower Development Officer II',
            'Medical Officer I',
            'Medical Officer II',
            'Medical Officer III',
            'Medical Officer IV',
            'Monitoring & Evaluation Officer II',
            'Monitoring & Evaluation Officer III',
            'Nurse I',
            'Nurse II',
            'Nutritionist Dietitian I',
            'Nutritionist Dietitian II',
            'Nutritionist Dietitian III',
            'Physical Therapist II',
            'Planning Officer I',
            'Planning Officer II',
            'Planning Officer III',
            'Planning Officer IV',
            'Procurement Officer',
            'Project Development Officer I',
            'Project Development Officer II',
            'Project Development Officer III',
            'Project Development Officer IV',
            'Project Development Officer V',
            'Project Evaluation Officer I',
            'Project Evaluation Officer II',
            'Project Evaluation Officer III',
            'Project Evaluation Officer IV',
            'Psychologist I',
            'Social Marketing Officer',
            'Social Welfare Aide',
            'Social Welfare Assistant',
            'Social Welfare Officer I',
            'Social Welfare Officer II',
            'Social Welfare Officer III',
            'Social Welfare Officer IV',
            'Social Welfare Officer V',
            'Statistician Aide',
            'Statistician I',
            'Statistician II',
            'Supervising Administrative Officer',
            'Technical Facilitator',
            'Training Assistant',
            'Training Specialist I',
            'Training Specialist II',
            'Training Specialist III',
            'Training Specialist IV',
            'Utility Worker I',
            'Utility Worker II',
        ];

        foreach ($positions as $position) {
            Position::create([
                'name' => $position
            ]);
        }
    }
}
